server:
  compression:
    enabled: true
    mime-types: application/json,text/html,text/plain
    min-response-size: 40
  jetty:
    acceptors: 2
  port: 9900
elasticsearch:
  serverUri: "http://localhost:9200"
  connectTimeOut: 90000
  readTimeOut: 90000
  index: "compliancesearch"
  clusterName: "compliance"
  fileType: "files_v1"
  maxResultsToFetch: 2000
  onInsertReplaceExisting: true
  scrollSize: 2
  scrollTime: 1m
  


